pipeline {

    agent {
        kubernetes {
            label 'k8s-agent'
        }
    }

    parameters {
        string(name: 'NAMESPACE', defaultValue: 'staging', description: 'Kubernetes namespace to deploy into')
        string(name: 'MICROSERVICES_DIR', defaultValue: 'k8s', description: 'Folder containing microservices')
        string(name: 'CHART_NAME', defaultValue: 'simple-app', description: 'Helm chart name stored in Nexus')
        string(name: 'CHART_VERSION', defaultValue: '83', description: 'Helm chart version to deploy')
    }

    environment {
        HELM_VERSION = "3.15.3"
        KUBECONFIG = credentials('kubeconfig-jenkins')
        KUBE_CONTEXT = "kind-kind-multinode"
        NEXUS_URL = credentials('nexus-url')
        NEXUS_CRED = credentials('nexus-credentials') 
    }

    stages {
        stage('Add Nexus Helm Repo') {
            steps {
                container('helm') {
                  withCredentials([
                    usernamePassword(
                        credentialsId: 'nexus-credentials',
                        usernameVariable: 'NEXUS_USER',
                        passwordVariable: 'NEXUS_PASS'
                    ),
                    string(
                        credentialsId: 'nexus-url',
                        variable: 'NEXUS_URL'
                    ),
                    string (
                        credentialsId: 'helm-repo',
                        variable: 'HELM_REPO'
                    )
                ]) {
                    sh """
                    helm repo add ${CHART_NAME} http://${NEXUS_URL}/repository/${HELM_REPO}/ \
                    --username ${NEXUS_USER} --password ${NEXUS_PASS}
                    helm repo update
                    helm search repo ${HELM_REPO}
                    ls -lart
                    """
            }
        }
            }
        }

        stage('Deploy from Nexus') {
            steps {
                
                container('helm') {
                     withCredentials([
                            string (
                                credentialsId: 'helm-repo',
                                variable: 'HELM_REPO'
                            )
                        ]){
                    script {
                        sh "helm ls --kube-context kind-kind-multinode --kube-insecure-skip-tls-verify"

                        def baseDir = params.MICROSERVICES_DIR
                        def namespace = params.NAMESPACE
                        def chartName = params.CHART_NAME
                        def chartVersion = params.CHART_VERSION

                        def services = sh(script: "ls -1 ${baseDir}", returnStdout: true).trim().split("\n")

                        // for (svc in services) {
                            // echo "🚀 Deploying microservice: ${svc}"

                            // def svcPath = "${baseDir}/${svc}"
                            def folder = "simple-app"
                            def valuesFile = "${baseDir}/${folder}/app.yaml"
                            // def cmFile = "${svcPath}/configmap.yaml"
                            // def secretFile = "${svcPath}/secret.yaml"

                            // Apply ConfigMap if present
                            // if (fileExists(cmFile)) {
                            //     sh "kubectl apply -f ${cmFile} -n ${namespace} --context ${KUBE_CONTEXT}"
                            // }

                            // // Apply Secret if present
                            // if (fileExists(secretFile)) {
                            //     sh "kubectl apply -f ${secretFile} -n ${namespace} --context ${KUBE_CONTEXT}"
                            // }

                            // // Deploy using Helm from Nexus
                            // if (fileExists(valuesFile)) {
                            sh """
                                        helm upgrade --install ${chartName} http://${NEXUS_URL}/repository/${HELM_REPO}/${chartName} \
                                        --version ${chartVersion} \
                                        -f ${valuesFile} \
                                        --namespace ${namespace} \
                                        --atomic --timeout 10m \
                                        --kube-context kind-kind-multinode \
                                        --kube-insecure-skip-tls-verify
                            """
                            // } else {
                            //     echo "⚠️ Skipping ${svc}: No values.yaml found."
                            // }

                        // }
                        echo "✅ ${svc} deployed successfully."
                    }
                  }
                }
            
            }
        }
    }

    post{
            success {
                echo "Microservices deployed successfully from Nexus!"
            }
            failure {
                echo "Deployment failed."
            }
        }

}
