# Default values for simple-k8s-app.
image:
  repository: localhost:5000/simple-k8s-app  # default, overridden in CI
  tag: "1.0"                                 # default, overridden in CI
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
